jenkins:
  storageClass: jenkins-sc
  serviceAccount:
    create: false
    name: jenkins
    annotations: {}
    imagePullSecretName:
  serviceAccountAgent:
    create: true
    name: jenkins-saa
    annotations: {}
    imagePullSecretName:
  ingress:
    enabled: false
  agent:
    enabled: true
    image: "korekontrol/docker-jnlp-slave-docker"
    tag: "latest"
    workingDir: "/home/jenkins/agent"
